=== Kikyou645559030/gdzc/src/main/java/com/gdzc/study/heimaClass/testFile/test2.dtd
<!ELEMENT root (first+,second*)>
<!ELEMENT first (one?|two+|three*)>
<!ELEMENT second ((one|two|three)|one*)>
<!ELEMENT one (#PCDATA)>
<!ELEMENT two (#PCDATA)>
<!ELEMENT three (#PCDATA)>
<!ELEMENT four EMPTY>
<!ATTLIST first
        a ANY #REQUIRED<!--表示所有类型都可以-必填属性-->
        b CDATA #IMPLIED<!--表示字符串类型-选填属性-->
        id ID #REQUIRED<!--表示类型是ID-必填属性-->
        c (aa|bb|cc) #IMPLIED<!--表示只能是规定的类型之一-选填属性-->
        >

=== Kikyou645559030/gdzc/src/main/java/com/gdzc/study/heimaClass/testFile/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE root SYSTEM "src/main/java/com/gdzc/study/heimaClass/testFile/test2.dtd">-->
<root>
    <first>
        <one>一</one>
        <two>二</two>
        <three>三</three>
    </first>
    <second>
        <one>四</one>
        <two>五</two>
        <three>六</three>
    </second>
</root>
